### ISSUE TITLE
"Success" landing page after application submission

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/commissions#120]
After the form submit is successful, the applicant should be taken to a page that has a thank you message and a confirmation.

 - [x] Use `.then` or `await` the result of the `fetch` to see if the POST succeeded
 - [x] Use Next’s `Router` to `push` to a new page (like `/commissions/success`)
 - [x] Make a new page in the `pages` directory that renders the success message

**Comment by paylakatel** [comment]
This was dealt with when this project was moved to the [digital repo](https://github.com/CityOfBoston/digital)
