### ISSUE TITLE
Figure out "no appointees" on Boston Finance Commission

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/commissions#18]
<img width="718" alt="screen shot 2018-05-21 at 10 05 28 am" src="https://user-images.githubusercontent.com/260837/40311666-8e268122-5cde-11e8-82bc-a348f51d4a2d.png">

**Comment by paylakatel** [comment]
This commission and others like it have been made not "live", but we should still have a plan for this instance to future-proof ourselves.

If there are 0 members on a board or commission, can the table module display:
"There are no members appointed to this Board or Commission at this time." with a large link/button to Apply?
