### ISSUE TITLE
Implement UI for "Applicant Information" on apply form

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/commissions#42]
- [x] Make form elements appear in a component
- [x] Style them with the [Fleet pattern library](https://patterns.boston.gov/)

<img width="738" alt="screen shot 2018-05-30 at 10 47 25 am" src="https://user-images.githubusercontent.com/260837/40727881-e662f4dc-63f6-11e8-879e-d0525634e235.png">

**Comment by paylakatel** [comment]
This was dealt with when this project was moved to the [digital repo](https://github.com/CityOfBoston/digital)
