### ISSUE TITLE
Display required fields on application page.

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/commissions#92]
Display which fields are required on Application form. Death certs should have a style we can also use here.

**Comment by fionawhim** [comment]
Add:

```
                  <span className="t--req" aria-hidden>
                    Required
                  </span>
```

within the `<label>` to get the effect.

**Comment by paylakatel** [comment]
This was dealt with when this project was moved to the [digital repo](https://github.com/CityOfBoston/digital)
