### ISSUE TITLE
Submit application to the database

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/commissions#98]
There should be a "Submit" button at the bottom of the application page that brings a user to a success page. 

- [x] The text on the page should read:
_Thank you for applying to serve on a Board or Commission. We appreciate your willingness to make a difference in the City of Boston. If you have any questions about your application, contact boardsandcommissions@boston.gov._
 
- [x] When the form is submitted, the information should be saved in the boards and commissions database

**Comment by fionawhim** [comment]
Saving to the database:

 - [x] Make a new method in CommissionsDao called `submitApplication` or something like that. It should take one parameter, an object of the form data.
 - [x] The Hapi handler in `commissions-app.ts` should call `makeCommissionsDao()` to make a `CommissionsDao`. Then it should call the `submitApplication` method with the form data and `await` the result.
 - [ ] `submitApplication` should use `this.pool` to run a stored procedure. Look at Registry Cert’s RegistryOrders.js file for an example. It should call `input` to add each value to the request. Look at SQLPro for the list of parameters. Ignore the ones that aren't on the form.

**Comment by fionawhim** [comment]
Some of this may be in #121

**Comment by fionawhim** [comment]
Closed in CityOfBoston/digital#110
